# Structures

## Dicionários

In [1]:
dic = {'lista':[1, 2, 3], 'ajuda':['ajudas', 'ajudantes', 'ajudou']}

## If, Elif and Else

In [2]:
x = 4

if x > 7:
    y = 'Aprovado'
elif x > 4:
    y = 'Recuperação'
else:
    y = 'Reprovado'
y

'Reprovado'

## For and While

In [3]:
seq = [1, 2, 3, 4, 5, 6]

for i in seq:
    print(i)

1
2
3
4
5
6


In [4]:
i = 1

while i <= 5:
    print('i vale: {}'.format(i))
    i = i + 1

i vale: 1
i vale: 2
i vale: 3
i vale: 4
i vale: 5


In [5]:
x = [2, 4, 8, 10]

[i**2 for i in x]

[4, 16, 64, 100]

## Functions

In [6]:
def minha_func(param):
    print(param)

minha_func('Olá')

Olá


In [7]:
def minha_func(param):
    x = param ** 5 
    return x

minha_func(5)

3125

### Lambda

Lambda é uma forma simplificada de se escrever uma função, no entanto ela só pode ser usada naquela linha do código com uma única e específica função/aplicação.

In [8]:
##### Modo padrão de escrever uma função ####
def quadrado(var):
    return var ** 2

##### Modo função em uma linha ####
def quadrado(var): return var ** 2

##### utilizando o lambda ####
lambda var: var ** 2

<function __main__.<lambda>(var)>

### MAP

In [9]:
def quadrado(var):
    return var ** 2

seq = [1,2,3,4,5]

In [10]:
map(quadrado, seq)

In [11]:
# Para exibir os valores da função map, deve ser convertido em lista
list(map(quadrado, seq))

[1, 4, 9, 16, 25]

### Lambda and MAP

In [12]:
list(map(lambda x:x**2, seq))

[1, 4, 9, 16, 25]

### Lambda and Filter

In [13]:
list(filter(lambda x:x % 2 == 0, seq))

[2, 4]

### Methods

Métodos são funções específicas aninhadas dentro de uma classe para a qual elas foram criadas. Ao se adicionar um "." após a classe é possível acessar essas funções aninhadas

In [14]:
str = 'Olá, eu me chamo Fernando'

In [15]:
print(str.lower())
print(str.upper())
print(str.split())

olá, eu me chamo fernando
OLÁ, EU ME CHAMO FERNANDO
['Olá,', 'eu', 'me', 'chamo', 'Fernando']


## Exercícios

Responda as perguntas ou complete as tarefas descritas em negrito abaixo, use o método específico, se aplicável.

** Quanto é 7 elevado na potência 4? **

In [16]:
7 ** 4

2401

** Quebre a seguinte string em uma lista:**


In [17]:
s = "Olá, Pai!"
s = s.split()
type(s)

list

** Dada as variáveis:**

    Planeta = "Terra"
    Diametro = 12742

** Use .format() para printar a seguinte frase: **

    O diâmetro da terra é de 12742 kilômetros.

In [18]:
planeta = "Terra"
diametro = 12742

In [19]:
print('O diâmetro da {} é de {} quilômetros'.format(planeta, diametro))

O diâmetro da Terra é de 12742 quilômetros


** Dada a lista abaixo, use indexação para obter apenas a string "ola". **

In [20]:
lst = [1,2,[3,4],[5,[100,200,['olá']],23,11],1,7]

In [21]:
lst[3][1][2][0]

'olá'

** Dado o seguinte dicionário aninhado, extraia a palavra "hello" **

In [22]:
d = {'k1':[1,2,3,{'café':['banana','mulher','colher',{'alvo':[1,2,3,'olá']}]}]}

In [23]:
d['k1'][3]['café'][3]['alvo'][3]

'olá'

** Qual a principal diferença entre um dicionário e uma tupla? **

Cria dados imutáveis

** Construa uma função que retire o domínio dado um e-mail no seguinte formato: **

    user@domain.com
    
**Por exemplo, passando como parâmetro "user@domain.com" retornaria: domain.com**

In [24]:
email = 'user@domain.com'

def obterDominio(email):
    x = email.split('@')[-1] # é utilizado o -1 para retornar o ultimo '@' presente
    #x = x.pop() # eu havia usado o .pop para retornar o ultimo item da lista
    return(print('O domínio do email é: {}'.format(x)))

In [25]:
obterDominio(email)

O domínio do email é: domain.com


In [26]:
obterDominio('user@domain.com')

O domínio do email é: domain.com


** Crie uma função básica que retorna True se a palavra 'dog' estiver contida na string de entrada. Não se preocupe com os casos de extremos, como uma pontuação que está sendo anexada à palavra cão, mas que seja senível à caixa. **

In [27]:
def encontreCachorro(string):
    return 'cachorro' in string.lower()

In [28]:
encontreCachorro('Existe um cachorro aí?')

True

** Crie uma função que conta o número de vezes que a palavra "dog" ocorre em uma string. Novamente ignore os casos extremos. **

In [29]:
def contaCachorro(string):
    cont = 0
    for i in string.lower().split():
        if i == 'cachorro':
            cont = cont + 1
    return cont

In [30]:
contaCachorro('Esse cachorro é mais rápido que o outro cachorro')

2

** Use expressões lambda e a função filter () para filtrar as palavras de uma lista que não começa com a letra 's'. Por exemplo: **

    seq = ['sopa','cachorro','salada','gato','ótimo']

** Deveria ser filtrado para:**

    ['sopa','salada']

In [31]:
seq = ['sopa','cachorro','salada','gato','ótimo']

In [32]:
list(filter(lambda x: x[0] == 's', seq))

['sopa', 'salada']

### Problema final
** Você está dirigindo um pouco rápido demais, e um policial para você. Escreva uma função para retornar um dos 3 resultados possíveis: "Sem multa", "Pequena multa" ou "Multa Grande".
   Se a sua velocidade for igual ou inferior a 60, o resultado é "Sem multa". Se a velocidade for entre 61 e 80 inclusive, o resultado é "Multa Pequena". Se a velocidade é de 81 ou mais, o resultado é "Multa Grande". A menos que seja seu aniversário (codificado como um valor booleano nos parâmetros da função) - em seu aniversário, sua velocidade pode ser 5 maior em todos os casos. **

In [33]:
def capturar_velocidade(speed, is_birthday):
    if is_birthday:
        speed = speed - 5
    if speed > 80:
        return 'Multa Grande'
    if speed > 60:
        return 'Multa Pequena'
    else:
        return 'Sem Multa'
    pass

In [34]:
print(capturar_velocidade(65,False))
print(capturar_velocidade(81,False))
print(capturar_velocidade(65, True))

Multa Pequena
Multa Grande
Sem Multa


# Numpy Intro

In [35]:
import numpy as np

In [38]:
minha_lista = [1,2,3,4,5]

minha_matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [37]:
# Convertendo uma lista em array
np.array(minha_lista)

array([1, 2, 3, 4, 5])

In [41]:
# Convertendo uma lista em um array multidimensional
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.arange(0,10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [44]:
np.zeros(3)

array([0., 0., 0.])

In [47]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
np.random.rand(5)

array([0.50741318, 0.6785959 , 0.78734338, 0.51365816, 0.74621981])

In [56]:
np.random.randn(5)

array([-1.08604359, -1.01570098, -0.46119721, -0.42028877, -2.11622633])

In [58]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
# É possível efetuar operações entre arrays desde que eles possuam as mesmas dimensões
print(arr + arr)
print(arr - arr)
print(arr * arr)
print(arr / arr)
print(arr *3 )


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45]


/tmp/ipykernel_17098/3767794586.py:5: RuntimeWarning: invalid value encountered in true_divide
  print(arr / arr)


In [66]:
# O Numpy tem vários métodos embutidos na biblioteca
print(np.sqrt(arr))
print(np.exp(arr))
print(np.mean(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]
7.5
